apiVersion: v1
kind: Pod
metadata:
  name: "es-dispatcher"
  labels:
    application: "es-dispatcher"
spec:
  securityContext:
    fsGroup: 1000

  containers:
    - name: sbt
      image: 551806661322.dkr.ecr.eu-west-1.amazonaws.com/base-images/sbt:1.5.5
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1000m"